name: Generate Languages Metrics

on:
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Languages Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.recent.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_limit: 8

